### ISSUE TITLE
希望你关闭相关极客大挑战相关的文章

### ISSUE THREAD

**Issue by 490694561** [0xcreed/0xCreed.github.io#1]
比赛暂未结束望理解

**Comment by 0xcreed** [comment]
不好意思，是我疏忽了。真不是故意的！


 
---原始邮件---
发件人: "0xpoker"<notifications@github.com&gt;
发送时间: 2019年11月3日 23:39:13
收件人: "AssCreed/AssCreed.github.io"<AssCreed.github.io@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [AssCreed/AssCreed.github.io] 希望你关闭相关极客大挑战相关的文章 (#1)



比赛暂未结束望理解

**Comment by 490694561** [comment]
问题还不算特别大，赛后再放吧

**Comment by 0xcreed** [comment]
已经下线了。不好意思，表哥。


 
---原始邮件---
发件人: "0xpoker"<notifications@github.com&gt;
发送时间: 2019年11月3日 23:46:01
收件人: "AssCreed/AssCreed.github.io"<AssCreed.github.io@noreply.github.com&gt;;
抄送: "AssCreed"<792683096@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [AssCreed/AssCreed.github.io] 希望你关闭相关极客大挑战相关的文章 (#1)



问题还不算特别大，赛后再放吧

**Comment by leohearts** [comment]
> 已经下线了。不好意思，表哥。
> […](#)
> ---原始邮件--- 发件人: "0xpoker"<notifications@github.com&gt; 发送时间: 2019年11月3日 23:46:01 收件人: "AssCreed/AssCreed.github.io"<AssCreed.github.io@noreply.github.com&gt;; 抄送: "AssCreed"<792683096@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [AssCreed/AssCreed.github.io] 希望你关闭相关极客大挑战相关的文章 (#1) 问题还不算特别大，赛后再放吧 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

大哥，以后记得删历史记录==
虽然我发现的有点晚了，快结束了
